name: Checks

on:
  pull_request:
  merge_group:

jobs:

  check-changelogs:
    name: changelogs
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Install dependencies
      run: |
        sudo apt install -y fd-find

    - uses: actions/checkout@v4

    - name: git fetch
      run: git fetch origin main:main

    - name: Check changelogs
      run: ./scripts/check-changelogs.sh

  stylish-haskell:
    runs-on: ubuntu-22.04

    env:
      STYLISH_HASKELL_VERSION: "0.14.6.0"

    steps:
    - name: Set cache version
      run: |
        echo "CACHE_VERSION=hi5eTh3A" >> $GITHUB_ENV

    - name: "Install build environment (apt-get)"
      run: |
        sudo apt-get update
        sudo apt-get -y install fd-find

    - name: "Setup Haskell"
      uses: haskell-actions/setup@v2
      id: setup-haskell
      with:
        ghc-version: 9.6.3
        cabal-version: 3.10.1.0

    - name: "Setup cabal bin path"
      run: |
        echo "$HOME/.cabal/bin" >> $GITHUB_PATH

    - name: Download stylish-haskell
      run: |
        version="${{ env.STYLISH_HASKELL_VERSION }}"

        curl -sL \
          "https://github.com/haskell/stylish-haskell/releases/download/v$version/stylish-haskell-v$version-linux-x86_64.tar.gz" \
          | tar -C "/tmp" -xz

        echo "PATH=/tmp/stylish-haskell-v$version-linux-x86_64:$PATH" >> $GITHUB_ENV

    - name: "`stylish-haskell` version"
      run: |
        which stylish-haskell
        stylish-haskell --version

    - uses: actions/checkout@v4

    - name: "Run `stylish-haskell`"
      run: |
        ./scripts/check-stylish.sh
        git diff --exit-code
